"""add_quiz_sharing

Revision ID: 1a73bfcf7e15
Revises: 9c954e1dd206
Create Date: 2026-02-26 18:20:31.780044

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a73bfcf7e15'
down_revision: str | Sequence[str] | None = '9c954e1dd206'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('share_code', sa.String(length=12), nullable=True))
    op.add_column('quizzes', sa.Column('is_shared', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_quizzes_share_code'), 'quizzes', ['share_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quizzes_share_code'), table_name='quizzes')
    op.drop_column('quizzes', 'is_shared')
    op.drop_column('quizzes', 'share_code')
    # ### end Alembic commands ###
