"""add_composite_indexes_for_performance

Revision ID: 776727e8f77d
Revises: 1a73bfcf7e15
Create Date: 2026-02-26 22:55:40.278400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776727e8f77d'
down_revision: Union[str, Sequence[str], None] = '1a73bfcf7e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_quiz_attempts_user_quiz_created', 'quiz_attempts', ['user_id', 'quiz_id', 'created_at'], unique=False)
    op.create_index('ix_wrong_notes_user_mastered_review', 'wrong_answer_notes', ['user_id', 'is_mastered', 'next_review_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wrong_notes_user_mastered_review', table_name='wrong_answer_notes')
    op.drop_index('ix_quiz_attempts_user_quiz_created', table_name='quiz_attempts')
    # ### end Alembic commands ###
