"""add_sm2_srs_fields

Revision ID: a4f74e1470f2
Revises: a3da42008f20
Create Date: 2026-02-26 05:48:32.280477

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4f74e1470f2"
down_revision: str | Sequence[str] | None = "a3da42008f20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wrong_answer_notes",
        sa.Column("ease_factor", sa.Float(), server_default="2.5", nullable=False),
    )
    op.add_column(
        "wrong_answer_notes",
        sa.Column("interval_days", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###

    # Repair interval_days for existing rows based on old SRS_INTERVALS table
    op.execute("""
        UPDATE wrong_answer_notes
        SET interval_days = CASE
            WHEN consecutive_correct <= 1 THEN 1
            WHEN consecutive_correct = 2   THEN 3
            WHEN consecutive_correct = 3   THEN 7
            WHEN consecutive_correct = 4   THEN 14
            ELSE 30
        END
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wrong_answer_notes", "interval_days")
    op.drop_column("wrong_answer_notes", "ease_factor")
    # ### end Alembic commands ###
