"""add cascade deletes

Revision ID: cd88d6d28714
Revises: b435d94f9835
Create Date: 2026-02-24 21:36:46.626520

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd88d6d28714"
down_revision: str | Sequence[str] | None = "b435d94f9835"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("quiz_attempts_quiz_id_fkey"), "quiz_attempts", type_="foreignkey")
    op.create_foreign_key(None, "quiz_attempts", "quizzes", ["quiz_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(
        op.f("wrong_answer_notes_quiz_item_id_fkey"), "wrong_answer_notes", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "wrong_answer_notes", "quiz_items", ["quiz_item_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "wrong_answer_notes", type_="foreignkey")
    op.create_foreign_key(
        op.f("wrong_answer_notes_quiz_item_id_fkey"),
        "wrong_answer_notes",
        "quiz_items",
        ["quiz_item_id"],
        ["id"],
    )
    op.drop_constraint(None, "quiz_attempts", type_="foreignkey")
    op.create_foreign_key(
        op.f("quiz_attempts_quiz_id_fkey"), "quiz_attempts", "quizzes", ["quiz_id"], ["id"]
    )
    # ### end Alembic commands ###
