"""add_user_cascade_deletes

Revision ID: e4375d2b36e9
Revises: 2e1b59a4b41e
Create Date: 2026-02-26 00:20:19.715322

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4375d2b36e9"
down_revision: str | Sequence[str] | None = "2e1b59a4b41e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("documents_owner_id_fkey"), "documents", type_="foreignkey")
    op.create_foreign_key(None, "documents", "users", ["owner_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("quiz_attempts_user_id_fkey"), "quiz_attempts", type_="foreignkey")
    op.create_foreign_key(None, "quiz_attempts", "users", ["user_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(
        op.f("wrong_answer_notes_user_id_fkey"), "wrong_answer_notes", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "wrong_answer_notes", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "wrong_answer_notes", type_="foreignkey")
    op.create_foreign_key(
        op.f("wrong_answer_notes_user_id_fkey"), "wrong_answer_notes", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "quiz_attempts", type_="foreignkey")
    op.create_foreign_key(
        op.f("quiz_attempts_user_id_fkey"), "quiz_attempts", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.create_foreign_key(
        op.f("documents_owner_id_fkey"), "documents", "users", ["owner_id"], ["id"]
    )
    # ### end Alembic commands ###
